#!/bin/sh
PRINT_SERVER_ADDRESS="http://ioiprint:5000"

TMP_FILE="/tmp/`date '+%F_%T'`.pdf"

CONTESTANT_IP=`echo $5 | grep -oE "job-originating-host-name=(\w|\.)+" | sed -e "s/job-originating-host-name=//"`
CUPS_JOB_ID=$1

cat - > ${TMP_FILE}

SERVER_FILENAME=`curl --form "pdf=@${TMP_FILE}" --form "type=contestant" ${PRINT_SERVER_ADDRESS}/upload`

curl --data "filename=${SERVER_FILENAME}&ip=${CONTESTANT_IP}&cups_job_id=${CUPS_JOB_ID}" ${PRINT_SERVER_ADDRESS}/contestant
