#!/bin/bash
TMP_FOLDER="~/tmp/contestant"
TMP_FILE="${TMP_FOLDER}/`date '+%F_%T'`"
IP=`echo $5 | grep -oP "job-originating-host-name=\K(\w|\.)+"`
CUPS_JOB_ID=$1

cat - > ${TMP_FILE}
xvfb-run ioiprint contestant ${TMP_FILE} ${IP} ${CUPS_JOB_ID}
